### ISSUE TITLE
JOSS Review: Functions with no examples

### ISSUE THREAD

**Issue by rmflight** [UofABioinformaticsHub/strandCheckR#10]
There are a collection of functions with no examples:

* `calculateStrandCoverage`
* `calculateStrandNbReads`
* `concatenateAlignments`
* `getWinFromGranges`
* `getWinFromIRanges`
* `getWinFromReadInfo`
* `getWinOfAlignments`
* `keptProbaWin`

**Comment by tothuhien** [comment]
Hi Robert, I'm working on this issue but realised that those functions are not exported. They are just called from other main functions of the package and may be not necessarily useful in other contexts. So I'm wondering whether it's necessary to add the example for them? Thanks a lot.
Hien

**Comment by rmflight** [comment]
Yes, if they are not exported, then they probably dont need examples. But then I wouldn't have them in the function index for the package either.

I would either consider removing their roxygen2 documentation, or using the `internal` keyword to keep them out of the package help index. 

See https://stackoverflow.com/a/36702221/719383 http://r-pkgs.had.co.nz/man.html

**Comment by rmflight** [comment]
I would also consider exporting the GRanges and IRanges functions as those would be natural containers for power users to have data in, and having examples for them. But I am OK if they are not exported and don't have examples.

**Comment by tothuhien** [comment]
Thanks Robert for your suggestion. We have used internal keyword to hide those functions from the package help index. We also exported some functions (with example) that may be used separately at some points, as you suggested. I've changed a little bit some function names to distinguish some functions had similar names but did different things.
Cheers,
Hien
