### ISSUE TITLE
getWinInSequence roxygen content

### ISSUE THREAD

**Issue by smped** [UofABioinformaticsHub/strandCheckR#11]
Hi Hien,

I just noticed that the documentation section of `getWinInSequence.R` is commented out. Not sure why so thought I'd raise it as an issue. I figure you probably have a good reason so didn't want to mess with it.

Cheers,

Steve

**Comment by tothuhien** [comment]
Hi Steve, I don't think there's a particular reason for that. I've just put the documentation back again. It should be an internal function anyway. Thanks.
Hien

**Comment by smped** [comment]
Thanks Hien! Nearly there now...

**Comment by tothuhien** [comment]
Actually I think we commented the documentation just because we didn't want that method to be indexed in the package help page. But now we can do that by using internal keyword.
