### ISSUE TITLE
JOSS Review: no license file

### ISSUE THREAD

**Issue by rmflight** [UofABioinformaticsHub/strandCheckR#2]
Although the DESCRIPTION file lists the GPL (>= 2) license, the project is missing a proper LICENSE file with the text of the license.

Although CRAN & Bioconductor forbids including the full text of licenses that are already covered by CRAN approved licenses, one can use the `.Rbuildignore` file to keep the license file from being included in the built and checked package.

**Comment by tothuhien** [comment]
Thanks @rmflight for reviewing the package. @steveped has added the LICENSE file as you suggested. Please let us know if there's any other issue. 
Hien

**Comment by rmflight** [comment]
I'm working through the rest of the review now @tothuhien, and hope to have it done early next week.
