### ISSUE TITLE
JOSS Review: README remove dependency installation

### ISSUE THREAD

**Issue by rmflight** [UofABioinformaticsHub/strandCheckR#6]
Remove installing dependent packages in the README installation instructions (currently line 14 in README.md). Given that the package is on Bioconductor, I would include both the Bioconductor instructions and the `devtools::install_github` instructions. I used the `devtools::install_github` instructions, and all the dependencies were properly installed on a clean R installation, so the dependency installation line is no longer required.

**Comment by smped** [comment]
Hi Robert,
Thanks for going through everything so thoroughly. This has now been changed as of commit `c883c26808fe7234b6c6da60d5077a1d623c70f0` so hopefully that's another one to tick off the list.
Cheers,
Steve
