### ISSUE TITLE
JOSS Review: Community Guidelines

### ISSUE THREAD

**Issue by rmflight** [UofABioinformaticsHub/strandCheckR#7]
There is no `Contributing.md` file, or a statement regarding contributions in the README.md, or anything regarding reporting issues or submitting pull requests.

**Comment by smped** [comment]
As of commit `025581c` a `BugReports` line has been added to the `DESCRIPTION` file, and information regarding author contributions and support have also been added to `README.md`

**Comment by rmflight** [comment]
I think that satisfies the requirements for the review, and will close this issue.

I would encourage a bit more formality, and the use of a CONTRIBUTING or CONDUCT file that lays out the basic terms, including what kinds of contributions result in the person being added to the author list of the package.

See this [github post](https://help.github.com/articles/setting-guidelines-for-repository-contributors/), and an example on [other](https://github.com/rmflight/knitrProgressBar/blob/master/CONDUCT.md)
