### ISSUE TITLE
JOSS Review: Performance Claim

### ISSUE THREAD

**Issue by rmflight** [UofABioinformaticsHub/strandCheckR#8]
The primary performance claim is in this statement in their paper: *For a human RNA-seq bam file of ~4Gb, it takes less than 3 minutes to scan the whole file and return a Data Frame of about 1.5Gb*. I do not have access to this size of file, so I cannot check this claim. However, given that the software is making use of the `Rsamtools` and `GenomicRanges` packages for the quantification, I have no reason to question these claims. The authors might consider qualifying the claim by including information about the compute environment (CPU, RAM) that generated this level of performance.

**Comment by tothuhien** [comment]
I couldn't find the file of 4Gb that I've tested before, so I've used another human RNA-seq bam file and see the same performance. I've modified that in the paper and added the information about the computer I've used. 
Cheers,
Hien
